### ISSUE TITLE
test asl_Map hangs with maxconcurrency values != 0

### ISSUE THREAD

**Issue by iakkus** [knix-microfunctions/knix#114]
When maxconcurrency is set to 1, hangs by printing "Test 1/4" (i.e., first test tuple).
When maxconcurrency is set to 2 or 3, hangs by printing "Test 4/4" (i.e., fourth test tuple).

A recent PR #111 has fixed some indentation issues in FunctionWorker/StateUtils. However, it appears that the problem was already there (i.e., before the indentation fixes).

**Comment by manuelstein** [comment]
not sure if related, but I just fixed a slash "/" that was appearing in the workflow label of a kservice in https://github.com/knix-microfunctions/knix/commit/372e77151d1bbf343ecafafacb611391684869d9 and wouldn't deploy on k8s

**Comment by iakkus** [comment]
This was running on a single-host, bare metal setup, so probably not.

**Comment by iakkus** [comment]
Fixed by 6983c3d16dbee88ae4383f29c7d616fe0303a0d0.
