### ISSUE TITLE
Does it mean I deploy successful?

### ISSUE THREAD

**Issue by lambda7xx** [knix-microfunctions/knix#150]
- I deploy the knix on the aws ubuntu18, and the log is below
![567547d7b4bcd3ccf3e52bc50acf36e](https://user-images.githubusercontent.com/35867865/227679984-f107e77e-fd48-430b-90f9-abca7d3846f9.png)

- I open the http://<nginx-hostname>:<nginx_http_listen_port>/,the figure is below
![image](https://user-images.githubusercontent.com/35867865/227680018-b51684d0-f343-4eba-aa4b-ad62dcf6911b.png)

- I run ``` docker ps -a ``` and ``` docker image ls ```, the figure is below
![daf8cef196a96762f66c630c921d3ab](https://user-images.githubusercontent.com/35867865/227680066-5af4279d-e88b-40ca-8857-0e4ba2423a91.png)

Do these figures means I deplo knix successful?

sorry to bother you, @ruichuan @paarijaat  @iakkus @manuelstein @ksatzke  @abeckn @umutkarabudak. Thank you very much

**Comment by iakkus** [comment]
Go where knix is installed (probably /opt/knix/) and run start_all.sh as root.

Then you should see the knix management container running with 'docker ps'.
