### ISSUE TITLE
Please use the relative path in README.md

### ISSUE THREAD

**Issue by kingzevin** [knix-microfunctions/knix#2]
In `README.md`, please replace 
``` markdown
[Code of Conduct](https://github.com/knix-microfunctions/knix/CODE_OF_CONDUCT.md
```
with 
``` markdown
[Code of Conduct](./CODE_OF_CONDUCT.md
```

**Comment by iakkus** [comment]
Thanks for catching that! It is quite possible that there are similar issues in other README files. Please let us know if you would like to check and fix them.

**Comment by kingzevin** [comment]
OK. I'll finish it today.

**Comment by kingzevin** [comment]
I pulled a request just now. :)
