### ISSUE TITLE
browser CORS checks for GUI actions

### ISSUE THREAD

**Issue by iakkus** [knix-microfunctions/knix#23]
[Environment]: bare metal, Kubernetes (maybe)
[Known affected releases]: master (includes all releases)

The GUI is being served by the nginx component. However, the GUI actions interacting with the management service (e.g., function/workflow creation/upload, workflow deployment) are using the address of the management service, which may have a different address than the GUI. To accommodate this setup, the browser has to make a CORS check (i.e., by sending an OPTIONS request) **before** each management service call. As a result, the GUI becomes less responsive due to the 2 RTTs required for each such action.

One solution to this problem, as suggested by @manuelstein, is to make the http content type text/plain, so that the browser does not do CORS checks. For more information, refer to the following links:
[StackOverflow question](https://stackoverflow.com/questions/3076414/ways-to-circumvent-the-same-origin-policy)
[W3C working draft](https://www.w3.org/TR/access-control/)
[Quite old Mozilla post](https://humanwhocodes.com/blog/2010/05/25/cross-domain-ajax-with-cross-origin-resource-sharing/)

Another potential solution, again suggested by @manuelstein), is to utilize the service mesh in Kubernetes/Knative, but it is not clear at this point how this can be achieved.

Another solution is to redirect management service traffic through nginx (as a proxy pass). This solution requires a configuration change of the nginx site:
1) an upstream server group for management with each host running the management service
2) a new nginx location rule for "/management/" suffix to proxy the request to the management upstream server group

Another required change is to ensure that the gui serves the updated endpoint (i.e., /opt/knix/nginx/gui/app/endpoint.js): <GUI address> + "/management/". This update is to ensure that the nginx location rule can work correctly for any incoming requests via the GUI.

With the above changes, only the traffic for the management service will go through nginx. For the rest of the workflows, the browser might still do a CORS check for executing a request (because the workflow endpoints are still served directly); however, these requests are less frequent (i.e., only via the workflow execution window). Requests without browsers (e.g., wget, curl) and requests directly utilizing the workflow endpoint (e.g., new tab in a browser) remain unaffected and happen without CORS checks.

For the bare metal environment, ansible scripts for nginx as well as its configuration template would need to be updated.
For Kubernetes/Knative environment, the helm template for nginx needs to be updated.

**Comment by iakkus** [comment]
Started implementation on branch [feature/remove_CORS_for_management](https://github.com/knix-microfunctions/knix/tree/feature/remove_CORS_for_management).

Ansible scripts for bare metal environment have been updated to proxy traffic for management service through nginx. Tested to see that GUI actions that have management service calls no longer require an extra request.

**Comment by manuelstein** [comment]
@iakkus, thanks for writing up the issue.
Should we go back to funneling all requests through the nginx that serves the website? @ruichuan @paarijaat @abeckn

**Comment by manuelstein** [comment]
... given that the concern here is latency ...

**Comment by iakkus** [comment]
The bare metal environment has been modified to reflect the changes. A new workflow action has been also created for the GUI to call.

@manuelstein could you take a look at the helm nginx template?
