### ISSUE TITLE
Storage triggers for workflows

### ISSUE THREAD

**Issue by paarijaat** [knix-microfunctions/knix#31]
### Describe the feature

Allow workflows to be triggered by writing objects in KNIX's key-value store. Users should be allowed to create triggerable tables (from the GUI, CLI, or user code) and allow associating one or more workflows with those tables. Any key-value pair written to such a table will trigger the associated workflows asynchronously. 

### Changes to be made:

* Management service to have new actions:
  * addTriggerableTable
  * addStorageTriggerForWorkflow
  * removeTriggerableTable
  * removeStorageTriggerForWorkflow

* Erlang triggers to be updated
* GUI, CLI, and MicrofunctionAPI object to be updated

**Comment by paarijaat** [comment]
Backend implemented in 'feature/storage_triggers' branch. Triggerable Tables and triggerable counters can now be created by contacting the management service. Internally this will create a bucket with type 'default'. The special bucket types 'triggers' and 'mfn_counter_triggers' bucket type have been disabled. The 'default' bucket type and 'counters' bucket type are now associated with riak triggers. All writes to buckets of these types will trigger the post-commit riak trigger. Most of these triggers will be ignored as there will not be any associated workflows with these buckets.

**Comment by iakkus** [comment]
A few clarification questions:

1. Are the triggerable tables just key-value tables? Or could it also be a 'map'?

2. Does the user code also have access to the 'triggerable counters'? Or is it just internally used (e.g., parallel state)?

**Comment by iakkus** [comment]
The feature has been merged.
