### ISSUE TITLE
state names compatibility support

### ISSUE THREAD

**Issue by ksatzke** [knix-microfunctions/knix#39]
[Environment]: bare metal, Kubernetes (maybe)
[Known affected releases]: master (includes all releases)

### Describe the Issue
Allow KNIX state names to contain special characters (: ; , \ | ^ ~ $ # % & ` ", whitespace) as this is supported in state machine definitions in AWS StepFunctions service. Currently, ASL state machine definitions containing state names with special characters cannot be deployed.

### Changes to be made:
- Management service to allow for state names containing special characters in state names
- SandboxAgent to allow for state names containing special characters in state names

**Comment by iakkus** [comment]
Merged to 'develop' branch.
