### ISSUE TITLE
Nginx error during k8s deployment

### ISSUE THREAD

**Issue by hpthai7** [knix-microfunctions/knix#44]
## Context

The latest K8s deployment see an nginx error:

```bash
$ k get pods
NAME                      READY   STATUS             RESTARTS   AGE
nx-mfn-7858745f87-zgbz6   1/2     CrashLoopBackOff   5          4m52s

$ k logs --container nginx nx-mfn-7858745f87-zgbz6
2020/06/16 15:03:08 [emerg] 1#1: host not found in upstream "wf-mfn-management" in /etc/nginx/conf.d/mfn.conf:29
nginx: [emerg] host not found in upstream "wf-mfn-management" in /etc/nginx/conf.d/mfn.conf:29

```

## Expected behavior

Nginx server should be working.

**Comment by iakkus** [comment]
Did you manage to run the other components successfully (e.g., riak, data layer service)?

There are certain dependencies of the components to be fulfilled before they can start properly (i.e., riak needs to be started before data layer service, data layer service needs to be started before management, management needs to be started before nginx). So if one component fails to start, there is a good chance the others are also going to fail. There are already issues related to that (#40, #41), so I think this is not an issue of the nginx component, but some other component.

**Comment by iakkus** [comment]
This seems due to the management service failing and not starting properly.

@manuelstein: could this be related to the predel-job failing (issue #43)?

**Comment by iakkus** [comment]
We can update the nginx component to continue running even the upstream service is down and make it periodically try to reconnect.

**Comment by manuelstein** [comment]
So, as a clarification, the nginx container upstream configuration did not find a valid management service which didn't work for a chain of reasons (riak cluster not working->no datalayer->no management workflow).
