### ISSUE TITLE
GUI uses and shows static API document

### ISSUE THREAD

**Issue by iakkus** [knix-microfunctions/knix#45]
The GUI uses a static version of the MicroFunctionsAPI (for python and Java). As a result, it can quickly become outdated when there are API changes. In fact, the python API pages shows an outdated version. 

It would be better if we can re-generate the relevant html files during installation, similar to the way it is done for the SDK and CLI.

**Comment by abeckn** [comment]
Started implementation on branch [feature/api_doc_generation](https://github.com/knix-microfunctions/knix/tree/feature/api_doc_generation)

**Comment by iakkus** [comment]
Merged to 'develop'.
