### ISSUE TITLE
Deleting user accounts

### ISSUE THREAD

**Issue by iakkus** [knix-microfunctions/knix#5]
[Environment]: Kubernetes, bare metal
[Known affected releases]: master (includes all releases)

In the current management service, there is no way to delete a user’s account and associated data. A corresponding action would need to identify the data items as well as any other metadata specific to this user and delete them from the data layer. 

Besides the management service, this change would have an effect on the GUI, and possibly the SDK and CLI.

**Comment by iakkus** [comment]
Started implementation at branch [feature/delete_account](https://github.com/knix-microfunctions/knix/tree/feature/delete_account).

**Comment by ksatzke** [comment]
Started development at branch feature/ASL_Map_state

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Istemi Ekin Akkus <notifications@github.com>
Gesendet: Thursday, May 7, 2020 5:14:08 PM
An: knix-microfunctions/knix <knix@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [knix-microfunctions/knix] Deleting user accounts (#5)


Started implementation at branch feature/delete_account<https://github.com/knix-microfunctions/knix/tree/feature/delete_account>.

**Comment by manuelstein** [comment]
Should this include removing the logs from Elasticsearch?
