### ISSUE TITLE
add bulk action capability to GUI storage objects

### ISSUE THREAD

**Issue by iakkus** [knix-microfunctions/knix#72]
Right now, each storage object has its own actions: 'edit', 'download', 'delete'

Bulk actions are not possible, such that if a user wants to delete a lot of items, she needs to do it one by one.

It would be great if the GUI were to support to 'download' and 'delete' operations in bulk.

**Comment by iakkus** [comment]
@abeckn , how feasible is this?

**Comment by abeckn** [comment]
Definitely feasible. I have to take a look at how to handle this with our current pagination approach, but it would look like in the screenshot below. 

![bulk_action](https://user-images.githubusercontent.com/63831049/87627950-82aec380-c6f5-11ea-8142-b1224685ded3.png)

**Comment by iakkus** [comment]
That looks good, thanks!

Regarding pagination, I think even bulk actions for a single page would be useful. 

The pagination already works when a single item is deleted, so that the first item from the next page is already pulled to that first page. Hopefully, it will be the case when multiple items are deleted as well.

**Comment by iakkus** [comment]
Gentle ping @abeckn.

**Comment by iakkus** [comment]
The private storage as well as CRDTs are now visible via the GUI. This might need to be reflected on the solution here as well.
