### ISSUE TITLE
Enable AWS Lambda context object compatibility

### ISSUE THREAD

**Issue by ksatzke** [knix-microfunctions/knix#80]
KNIX python function handlers have a context object just like AWS Lambda python and Java function handlers have, but some of the properties of the corresponding [AWS context object](https://docs.aws.amazon.com/de_de/lambda/latest/dg/python-context.html) are still missing in the KNIX implementation. 

This implementation task will be performed in the [feature/AWS_API_compatibility](https://github.com/knix-microfunctions/knix/tree/feature/AWS_API_compatibility) branch, targeting full Lambda object compatibility for KNIX.

**Comment by iakkus** [comment]
From the changes I saw, it looks like we also need to update the API object for the Java functions in KNIX.

Are there other changes/additions that need to be done? If not, I can take the modified Python API and apply it for Java functions.

**Comment by ksatzke** [comment]
Hi Ekin,
as you can see in the implementation a lot of the emulated context object properties are hardcoded.

One thing that comes into mind immediately is a proper support of function versioning/aliasing - which still needs to be added to KNIX.

BR Klaus

**Comment by iakkus** [comment]
I meant something like this: https://docs.aws.amazon.com/en_us/lambda/latest/dg/java-context.html

**Comment by ksatzke** [comment]
Hi Ekin,
when looking at https://docs.aws.amazon.com/en_us/lambda/latest/dg/python-context.html for comparison the context object for Java looks quite different, e.g. in terms of use method names. Plus, there are no properties in the context object for Java at all.
Could it be handled with a simple case distinction in MicrofunctionsAPI.py? I thinks I’ve made changes only to this file.

BR Klaus

**Comment by iakkus** [comment]
I added the modifications necessary for the Java worker, but it needs testing.

**Comment by iakkus** [comment]
Added Java context test as well.

I am not sure whether we are going to support different versions etc. as intended, but at this point, we wouldn't have to worry about existing code breaking due to migration to knix.

I think we can merge this.

@ksatzke : Could you open a PR please?

**Comment by ksatzke** [comment]
Hi Ekin, thanks for this – OK, will do.

BR Klaus
