### ISSUE TITLE
External triggers for workflow, based on message queue triggers

### ISSUE THREAD

**Issue by paarijaat** [knix-microfunctions/knix#82]
**Feature:** Allow workflows to be invoked by subscribing to external message queues, such as RabbitMQ, Kafka, etc.

A separate component called `TriggersFrontend` will be added to knix that will subscribe to the extenal queues and call knix workflows via http. A single replica of the new-frontend will be able to subscribe to multiple queue subscriptions requests, i.e., RabbitMQ subscription, Kafka subscriptions, etc. being handled by the same replica. The mappings will be maintained in datalayer. The management service will be contacted first to create an association between an external queue and workflow (similar to storage triggers). The management service will then signal the `TriggersFrontend` to actually subscribe. To begin with atleast one instance of the `TriggersFrontend` will run in knix. If there are no subscribers then it will occupy minimal resources. It could also be turned into a knative service and can be potentially scaled down to zero as an optimization. 

Each `TriggersFrontend` will expose an http endpoint. In Kubernetes world, this endpoint will be a k8s service endpoint. Management service will call that http endpoint to signal ‘add-subscription’ intention. K8s will load balance these requests among the `TriggersFrontend` replicas. In response to this http request, management service will receive the address of the replica answering the request. This address will be used to send ‘remove-subscription’ and ‘status-check’ requests subsequently. 

Whenever a new `TriggersFrontend`  (first or a replica) will come up, it will contact the management service to register itself. As a response, management service could provide an initial list of subscriptions or the replica would wait for ‘add-subscription’ requests.

Addition of new replicas would be done based on memory and cpu (standard horizontal pod autoscaling) to being with. More complex policies could be added later. If a replica is being gracefully shutdown then it would indicate that to the management service as well.

The `TriggersFrontend`s would also regularly report health status back to management service.  Management service will also regularly check the status of registered `TriggersFrontend`s. If a replica goes down without informing the management service (and when the management originating ‘status-check’ request fails), it will take the subscriptions assigned to that replica and broadcast them to the http service endpoint again for others to pick up.

For management service to send periodic health check, I intend to create a simple sub-workflow (within the management service) being launched when the first `TriggersFrontend` registers. This sub-workflow will have two states, first will be an ASL wait state (which waits for say 5 seconds), followed by a state that sends the health check ping to all the registered `TriggersFrontend` (addresses read from the data layer). After that it loops back to the wait state. To stop this loop, we can remove all addresses from the datalayer. This need not be a two state sub-workflow and could be a single state sub-workflow as well.

`TriggersFrontend` intetionally will not depend on the datalayer. Management service would act as the management plane for the `TriggersFrontend`s and it makes the scaling straightforward. 

More details to be added later.

**Comment by paarijaat** [comment]
'feature/triggers_frontend' branch, created with the first cut of the independent TriggersFrontend component. Still working on management service integration.

**Comment by iakkus** [comment]
Merged.
