### ISSUE TITLE
adding ASL Map State support 

### ISSUE THREAD

**Issue by ksatzke** [knix-microfunctions/knix#9]
[Environment]: Kubernetes, bare metal
[Known affected releases]: master (includes all releases)

In the current implementation there is no support for the ASL Map state yet. Map state has recently been added to ASL definition and to the AWS StepFunctions service, and adds some dynamic parallelism to ASL.

Besides the KNIX FunctionWorker, this change will have an effect on the KNIX GUI, the SDK and the CLI.

**Comment by iakkus** [comment]
Merged into 'develop' branch.
