### ISSUE TITLE
Triggers SDK update (storage, message queues, timers)

### ISSUE THREAD

**Issue by iakkus** [knix-microfunctions/knix#94]
A recent PR(#90) provides the capability of creating workflow triggers based on storage operations.

Similarly, PR(#93) provided the capability of creating workflow triggers based on external message queues and timers.

However, the SDK changes reflecting that capability is still missing and needs to be double-checked.

**Comment by manuelstein** [comment]
The functions available in the management service to create/delete/bind/unbind sources (buckets,triggers) are covered by the API now and have been successfully used in examples with [this commit](https://github.com/knix-microfunctions/knix/commit/dcb131cf8f3c1b7e54076fef658031da46b55e5e)
Also the CLI now supports all these actions with [this commit](https://github.com/knix-microfunctions/knix/commit/f91984028cc08837a1e528bec2ff1a8bacb555a5)
