### ISSUE TITLE
Triggers API object update for Java (storage, message queues, timers)

### ISSUE THREAD

**Issue by iakkus** [knix-microfunctions/knix#95]
A recent PR(#90) provides the capability of creating workflow triggers based on storage operations.

Similarly, PR(#93) provided the capability of creating workflow triggers based on external message queues and timers.

However, the API needs to be updated to reflect the changes for Java functions.

**Comment by iakkus** [comment]
There is a problem regarding the message queue/timer trigger creation. These API calls return a tuple (bool and string), which is not straightforward (not possible?) to represent in thrift.

The storage triggers API calls return a single boolean to return success/failure. Perhaps, it is better to also do that for the other triggers.

**Comment by ruichuan** [comment]
Returning a tuple in Thrift can be done via a self-defined struct like what
we did for KeyValuePair, etc.

**Comment by iakkus** [comment]
Ah, that's true. I had forgotten about that. Thanks!

Nonetheless, I think the API calls (storage triggers and external triggers) should be consistent: either both should use just a boolean for success, or both should use the tuple.

**Comment by ruichuan** [comment]
Yes, absolutely.

**Comment by iakkus** [comment]
Needs java tests.
